# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: xsigns.fewo::lang.booking.name

# Model Form Field configuration
form: ~/plugins/xsigns/fewo/models/restzahlungenlist/fields.yaml

# Model Class name
modelClass: xsigns\fewo\Models\RestzahlungenList

# Default redirect location
defaultRedirect: xsigns/fewo/restzahlungen

preview:
    title