# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: xsigns.fewo::lang.votings.name

# Model Form Field configuration
form: ~/plugins/xsigns/fewo/models/votings/fields.yaml

# Model Class name
modelClass: xsigns\fewo\Models\Votings

# Default redirect location
defaultRedirect: xsigns/fewo/votings

#update:
#    title: xsigns.fewo::lang.booking.update_booking
#    redirect: xsigns/fewo/bookinglist
#    redirectClose: xsigns/fewo/bookinglist

preview:
    title