<?php namespace Xsigns\Fewo\Updates;
use DB;
use Schema;
use October\Rain\Database\Updates\Migration;

class CreateTables extends Migration
{
    public function up()
    {
        Schema::create('xsigns_fewo_ang',function($table){
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('tstamp')->useCurrent();
            $table->integer('ang_id')->unsigned()->index();
            $table->string('ang_art', 100)->index();
            $table->date('ang_von');
            $table->date('ang_bis');
            $table->integer('ang_tagebuchen')->unsigned();
            $table->integer('ang_tagezahlen')->unsigned();
            $table->decimal('ang_festpreis', 9, 2)->default(0.00);
            $table->integer('ang_aktiv')->unsigned();
            $table->decimal('ang_prozent', 5, 2)->default(0.00);
            $table->integer('ang_erwachsene')->unsigned();
            $table->integer('ang_kinder')->unsigned();
            $table->integer('ang_mehrfach')->unsigned();
            $table->integer('ang_laenger')->unsigned();
            $table->string('ang_sort', 30)->index();
            $table->string('ang_alias', 250)->nullable();
        });
        Schema::create('xsigns_fewo_anglang',function($table){
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('tstamp')->useCurrent();
            $table->integer('angid')->unsigned()->index();
            $table->string('lang', 3)->index();
            $table->string('titel', 200)->index();
            $table->text('beschreibung');
            $table->index(['angid', 'lang']);
        });
        //xsigns_fewo_angebote_objekte
        Schema::create('xsigns_fewo_angobj',function($table){
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('tstamp')->useCurrent();
            $table->integer('ango_angid')->unsigned()->index();
            $table->integer('ango_objid')->unsigned()->index();
            $table->date('ango_von');
            $table->date('ango_bis');
            //$table->index(['ango_angid', 'ango_objid']);
        });
        Schema::create('xsigns_fewo_art', function($table) {
            $table->engine = 'InnoDB';
            $table->integer('artid')->unsigned()->index();
            $table->string('art_kurz',20)->index();
        });
        Schema::create('xsigns_fewo_artlang', function($table) {
            $table->engine = 'InnoDB';
            $table->integer('artid')->unsigned()->index();
            $table->string('name',100)->index();
            $table->string('lang',3);
            $table->index(['artid', 'lang']);
        });
        Schema::create('xsigns_fewo_auskat', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('auskatid')->unsigned()->index();
            $table->string('auskat_sort', 10);
        });
        Schema::create('xsigns_fewo_auskatlang', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('katid')->unsigned()->index();
            $table->string('name', 200);
            $table->string('lang',3);
            $table->index(['katid', 'lang']);
        });
        Schema::create('xsigns_fewo_aus', function($table) {
            $table->engine = 'InnoDB';
            $table->integer('ausid')->unsigned()->index();
            $table->integer('aus_katid')->unsigned()->index();
            $table->string('aus_sort', 20)->default('')->index();
            $table->string('aus_name',250)->default('');
            $table->index(['ausid', 'aus_katid']);
        });
        Schema::create('xsigns_fewo_auslang', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('ausid')->unsigned()->index();
            $table->string('name', 200)->default('');
            $table->string('lang',3)->default('');
            $table->index(['ausid', 'lang']);
        });
        Schema::create('xsigns_fewo_bewpunkte', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('tstamp')->useCurrent();
            $table->integer('bewertung_id')->unsigned()->index();
            $table->decimal('punkte', 5, 2)->default(0.00);;
            $table->integer('option_id')->unsigned()->index();
            $table->integer('pid');
        });
        Schema::create('xsigns_fewo_bew', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('tstamp')->useCurrent();
            $table->integer('obj_id')->unsigned()->index();
            $table->integer('aktiv')->unsigned()->index();
            $table->string('betreff', 250)->index();
            $table->text('nachricht');
            $table->text('antwort');
            $table->date('datum');
            $table->string('mail',250);
            $table->string('gastname',250);
            $table->integer('pid');
            $table->string('ort',200);
        });
        Schema::create('xsigns_fewo_bewopt', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('id')->unsigned();
            $table->string('titel',120);
            $table->string('sortindex');
            $table->string('lang',3);
        });
        Schema::create('xsigns_fewo_bewoptlang', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('optionsid');
            $table->string('titel',120);
            $table->string('lang',3);
        });
        Schema::create('xsigns_fewo_buchung', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('vtyp',2);
            $table->date('erfasst');
            $table->integer('objektid')->unsigned()->index();
            $table->string('firma',30)->nullable();
            $table->string('anrede',30)->nullable();
            $table->string('titel',30)->nullable();
            $table->string('vorname',30)->nullable();
            $table->string('zuname',30)->nullable();
            $table->date('gebdatum');
            $table->string('strasse',200)->nullable();
            $table->string('plz',10)->nullable();
            $table->string('ort',200)->nullable();
            $table->string('iban',60)->nullable();
            $table->string('land',3)->nullable();
            $table->string('tel',35)->nullable();
            $table->string('mobil',35)->nullable();
            $table->string('perso',50)->nullable();
            $table->string('email',250)->nullable();
            $table->date('anreise');
            $table->date('abreise');
            $table->integer('erwachsene')->unsigned();
            $table->integer('kinder')->unsigned();
            $table->integer('kleinkinder')->unsigned()->nullable();
            $table->text('leistungen');
            $table->text('mitreisende');
            $table->text('artikel');
            $table->string('orderHash',250)->nullable();
            $table->text('nachricht');
            $table->string('typeof',250);
            $table->integer('sync');
            $table->integer('userid')->unsigned();
            $table->integer('angebotid')->unsigned();
            $table->string('rueckruf',250)->nullable();
            $table->string('register',1)->nullable();
            $table->decimal('objektpreis',9,2)->default(0.00);
            $table->decimal('angebotpreis',9,2)->default(0.00);
            $table->decimal('anzpreis',9,2)->default(0.00);;
            $table->decimal('leistpreis',9,2)->default(0.00);
            $table->decimal('summe',9,2)->default(0.00);
            $table->text('zuschlaege');
            $table->decimal('zuschlagpreis',9,2)->default(0.00);
            $table->decimal('restzahlung',9,2)->default(0.00);
            $table->text('versicherung');
            $table->decimal('gezahlt',9,2)->default(0.00);
            $table->decimal('kaution',9,2)->default(0.00);
            $table->decimal('gebuehr',9,2)->default(0.00);
            $table->integer('gebuehr_ausanz')->unsigned();
            $table->string('gezahltmit',120)->nullable();
            $table->string('gezahltID',120)->nullable();
            $table->date('gezahltam');
            $table->string('paypal_id',80)->nullable();
            $table->string('paypal_payername',100)->nullable();
            $table->string('paypal_payerfirstname',250)->nullable();
            $table->string('paypal_payeremail',250)->nullable();
            $table->string('hobex_id',20)->nullable();
            $table->string('hobex_gen',20)->nullable();
            $table->string('hobex_stan',20)->nullable();
            $table->string('hobex_kkg',40)->nullable();
            $table->string('hobex_card',25)->nullable();
            $table->string('hobex_txid',20)->nullable();
            $table->string('receiptnumber',20)->nullable();
            $table->string('language',3)->nullable();
            $table->string('zahlungswunsch',50)->nullable();
            $table->string('newsletter',50)->nullable();
            $table->string('optionen',50)->nullable();
            $table->integer('temp_buid')->unsigned()->index();
            $table->integer('temp_zahlid')->unsigned()->index();
        });
        Schema::create('xsigns_fewo_entf', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('id')->unsigned()->index();
            $table->string('entf_strasse', 200);
            $table->string('entf_ort', 200);
            $table->string('entf_plz', 10);
            $table->string('entf_land', 3);
            $table->string('entf_lat', 60);
            $table->string('entf_lng', 60);
            $table->string('entf_url', 250);
            $table->string('entf_sort', 20);
            $table->string('entf_address', 250);
            $table->string('entf_countrycode', 10);
            $table->index(['entf_lat', 'entf_lng']);
        });
        Schema::create('xsigns_fewo_entflang', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('entfid')->unsigned()->index();
            $table->string('lang', 3);
            $table->string('name', 250);
            $table->text('beschreibung');
            $table->index(['entfid', 'lang']);
        });
        Schema::create('xsigns_fewo_gast', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('tstamp')->useCurrent();
            $table->integer('gast_id')->unsigned()->index();
            $table->string('gast_titel', 60)->nullable();
            $table->string('gast_anrede', 60)->nullable();
            $table->string('gast_vorname', 120)->nullable();
            $table->string('gast_name', 120)->index();
            $table->string('gast_strasse', 200)->nullable();
            $table->string('gast_plz', 10)->nullable();
            $table->string('gast_ort', 200)->nullable();
            $table->string('gast_land', 3)->nullable();
            $table->string('gast_tel', 25);
            $table->string('gast_mobil', 25);
            $table->string('gast_mail', 250);
            $table->string('gast_hashcode', 120)->nullable();
            $table->integer('gast_gesperrt')->unsigned();
        });
        Schema::create('xsigns_fewo_vorggesendet',function ($table){
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('vorgid')->unsigned()->index();
            $table->integer('bewertung')->unsigned();
            $table->integer('anschreiben')->unsigned();
        });

        Schema::create('xsigns_fewo_ha', function($table) {
            $table->engine = 'InnoDB';
            $table->integer('id')->unsigned()->index();
            $table->string('haus_titel', 250);
            $table->string('haus_name', 250)->index();
            $table->string('haus_alias', 250)->index();
            $table->string('haus_strasse', 250);
            $table->string('haus_plz', 10);
            $table->string('haus_land', 3);
            $table->string('haus_ort', 250);
            $table->string('haus_tel', 25);
            $table->string('haus_fax', 25);
            $table->string('haus_mail', 25);
            $table->string('haus_lat', 60);
            $table->string('haus_lng', 60);
            $table->string('haus_sort', 20)->index();
        });
        Schema::create('xsigns_fewo_halang', function($table) {
            $table->engine = 'InnoDB';
            $table->integer('hausid')->unsigned()->index();
            $table->string('lang', 3)->index();
            $table->string('name',250);
            $table->text('beschreibung');
            $table->text('kurz');
            $table->text('seo');
        });

        Schema::create('xsigns_fewo_kunde', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('tstamp')->useCurrent();
            $table->string('firma', 160);
            $table->string('vorname', 120);
            $table->string('name', 120);
            $table->string('str', 200);
            $table->string('plz', 10);
            $table->string('ort', 200);
            $table->string('land', 3);
            $table->string('tel', 25);
            $table->string('fax', 25);
            $table->string('mail', 160);
            $table->string('bankinhaber', 200);
            $table->string('bank', 200);
            $table->string('bankiban', 60);
            $table->string('steuernummer', 60);
            $table->decimal('anzahlung_proz', 5, 2)->default(0.00);
            $table->integer('anzahlung_objpreis')->unsigned()->default(0);
        });
        Schema::create('xsigns_fewo_la', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('id')->unsigned()->index();
            $table->string('sort', 10);
            $table->index(['id', 'sort']);
        });
        Schema::create('xsigns_fewo_lalang', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('lageid')->unsigned()->index();
            $table->string('lang', 3);
            $table->string('name', 250);
            $table->index(['lageid', 'lang']);
        });
        Schema::create('xsigns_fewo_le', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('leistid')->unsigned()->index();
            $table->decimal('leist_mwst',5, 2)->default(0.00);
            $table->decimal('leist_preis', 9, 2)->default(0.00);
            $table->integer('leist_person')->unsigned();
            $table->integer('leist_artid')->unsigned()->index();
            $table->integer('leist_tag')->unsigned();
            $table->integer('leist_anfrage')->unsigned();
            $table->integer('leist_sort')->unsigned()->index();
        });
        Schema::create('xsigns_fewo_leart', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('leistart_id')->unsigned()->index();
            $table->string('leistart_titel', 250);
            $table->integer('leistart_aktiv')->unsigned();
        });
        Schema::create('xsigns_fewo_lelang', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('leistid')->unsigned()->index();
            $table->string('titel', 200);
            $table->string('titel2', 200)->nullable();
            $table->string('lang', 3)->index();
            $table->text('beschreibung');
            $table->index(['leistid', 'lang']);
        });

        Schema::create('xsigns_fewo_obj', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('id')->unsigned()->index();
            $table->string('obj_alias', 250)->index();
            $table->string('obj_name', 200);
            $table->string('obj_intnr', 60)->nullable();
            $table->integer('obj_artid')->unsigned()->default(0)->index();
            $table->integer('obj_typid')->unsigned()->default(0)->index();
            $table->integer('obj_ortid')->unsigned()->default(0)->index();
            $table->integer('obj_verart')->unsigned();
            $table->decimal('obj_zimmer', 5, 2)->default(0.00)->index();
            $table->integer('obj_betten')->unsigned()->default(0)->index();
            $table->integer('obj_personen')->unsigned()->default(0)->index();
            $table->integer('obj_optbelegung')->default(0)->unsigned();
            $table->integer('obj_kinder')->unsigned()->default(0)->index();
            $table->integer('obj_kleinkinder')->unsigned()->default(0)->index();
            $table->integer('obj_erwachsene')->unsigned()->default(0)->index();
            $table->decimal('obj_groesse', 5, 2)->default(0.00);
            $table->decimal('obj_etage', 5, 2)->default(0.00)->index();;
            $table->string('obj_etagetext', 60);
            $table->integer('obj_aktiv')->unsigned()->default(0)->index();
            $table->integer('obj_sterne')->unsigned()->default(0)->index();
            $table->integer('obj_badezimmer')->unsigned()->default(0)->index();
            $table->integer('obj_schlafzimmer')->unsigned()->default(0)->index();
            $table->integer('obj_exclusiv')->unsigned()->default(0);
            $table->integer('obj_userid')->unsigned()->default(0);
            $table->string('obj_strasse', 170);
            $table->string('obj_plz', 10);
            $table->string('obj_land', 3);
            $table->string('obj_ort', 160);
            $table->integer('obj_regionid')->unsigned()->default(0)->index();
            $table->string('obj_lat', 40);
            $table->string('obj_lng', 40);
            $table->integer('obj_hausid')->unsigned()->index();
            $table->decimal('obj_kaution', 9, 2)->default(0.00);
            $table->string('obj_sort', 30);
            $table->time('obj_anreisevon');
            $table->time('obj_anreisebis');
            $table->time('obj_abreisevon');
            $table->time('obj_abreisebis');
            $table->string('obj_atraveo', 20);
            $table->string('obj_youtube', 155);
            $table->string('obj_registriernr',100)->default('');
            $table->index(['id', 'obj_alias', 'obj_sort','obj_aktiv'],'objekte1');
            $table->index(['obj_personen', 'obj_zimmer'],'objekte3');
            $table->index(['obj_betten','obj_schlafzimmer','obj_badezimmer'],'objekte4');
            $table->index(['obj_schlafzimmer','obj_badezimmer','obj_zimmer'],'objekte5');
            $table->index(['obj_personen','obj_badezimmer','obj_zimmer'],'objekte6');
            $table->index(['obj_alias','id'],'objekte7');
        });
        Schema::create('xsigns_fewo_objaus',function($table){
            $table->engine = 'InnoDB';
            $table->integer('objid')->unsigned()->index();
            $table->integer('ausid')->unsigned()->index();
            $table->string('wert', 40);
            $table->index(['objid','ausid']);
        });
        Schema::create('xsigns_fewo_objbleist',function($table){
            $table->engine = 'InnoDB';
            $table->integer('objid')->unsigned()->index();
            $table->integer('leistid')->unsigned()->index();
            $table->decimal('anz',7,2)->default(0.00)->unsigned();
            $table->index(['objid','leistid']);
        });
        Schema::create('xsigns_fewo_objentf',function($table){
            $table->engine = 'InnoDB';
            $table->integer('objid')->unsigned()->index();
            $table->integer('entfid')->unsigned()->index();
            $table->decimal('km',7,2)->default(0.00)->unsigned();
            $table->index(['objid','entfid']);
            $table->index(['objid','entfid','km']);
        });
        Schema::create('xsigns_fewo_objlagen',function($table){
            $table->engine = 'InnoDB';
            $table->integer('objid')->unsigned()->index();
            $table->integer('lageid')->unsigned()->index();
            $table->index(['objid','lageid']);
        });
        Schema::create('xsigns_fewo_objlang', function ($table) {
            $table->engine = 'InnoDB';
            $table->integer('objid')->unsigned()->index();
            $table->string('titel', 200);
            $table->string('titel2', 200);
            $table->string('lang', 3)->index();
            $table->text('beschreibung');
            $table->text('kurz');
            $table->text('seo');
            $table->text('lage');
            $table->text('anfrage');
            $table->text('preis1');
            $table->text('preis2');
            $table->text('baeder');
            $table->text('schlafzimmer');
            $table->text('html1');
            $table->text('html2');
            $table->text('html3');
            $table->text('innen');
            $table->text('aussen');
            $table->index(['objid', 'lang']);
        });
        Schema::create('xsigns_fewo_objleist',function($table){
            $table->engine = 'InnoDB';
            $table->integer('objid')->unsigned()->index();
            $table->integer('leistid')->unsigned()->index();
            $table->decimal('anz',7,2)->default(0.00)->unsigned();
            $table->index(['objid','leistid']);
        });
        Schema::create('xsigns_fewo_objstat', function($table){
            $table->engine = 'InnoDB';
            $table->integer('objid')->unsigned()->index();
            $table->integer('geklickt')->unsigned()->default(0);
            $table->integer('angefragt')->unsigned()->default(0);
            $table->integer('gebucht')->unsigned()->default(0);
            $table->integer('wertung')->unsigned()->default(0);
            $table->integer('gemerkt')->unsigned()->default(0);

        });
        Schema::create('xsigns_fewo_objza', function($table) {
            $table->engine = 'InnoDB';
            $table->integer('objid')->unsigned()->index();
            $table->decimal('kaut', 9, 2)->default(0.00);
            $table->integer('kautwann')->unsigned();
            $table->decimal('anzproz', 9, 2)->default(0.00);
            $table->decimal('anzmin', 9, 2)->default(0.00);
            $table->integer('anzaus')->unsigned();
            $table->integer('anztage')->unsigned();
            $table->integer('anzwann')->unsigned();
            $table->integer('resttage')->unsigned();
            $table->integer('restwann')->unsigned();
        });

        Schema::create('xsigns_fewo_orte', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('ort_name', 250)->index();
            $table->string('ort_plz', 10);
            $table->string('ort_land', 3)->index();
            $table->index(['ort_name', 'ort_land']);
        });
        Schema::create('xsigns_fewo_preise', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('objid')->unsigned()->index();
            $table->date('von');
            $table->date('bis');
            $table->decimal('preis', 9, 2)->default(0.00);
            $table->integer('personen')->unsigned();
            $table->decimal('weitere', 9, 2)->default(0.00);
            $table->integer('mintage')->unsigned();
            $table->decimal('exportpreis', 9, 2)->default(0.00);
            $table->decimal('anzahlung', 9, 2)->default(0.00);
            $table->decimal('woche', 9, 2)->default(0.00);
            $table->integer('lueckenbok')->unsigned();
            $table->integer('anreise')->unsigned();
            $table->index(['objid', 'von', 'bis']);
        });
        Schema::create('xsigns_fewo_preiselang', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('preislng_preisid')->unsigned()->index();
            $table->integer('preislng_objid')->unsigned()->index();
            $table->string('preislng_titel', 250);
            $table->string('preislng_lang', 3);
            //$table->index(['preislng_preisid', 'preislng_lang']);
        });
        Schema::create('xsigns_fewo_reg', function($table){
            $table->engine = 'InnoDB';
            $table->integer('regionid')->unsigned()->index();
            $table->string('region_name', 200)->index();
            $table->string('region_alias', 200)->index();
            $table->string('region_sort', 200)->index();
        });
        Schema::create('xsigns_fewo_reglang', function($table) {
            $table->engine = 'InnoDB';
            $table->integer('regionid')->unsigned()->index();
            $table->string('lang', 3)->index();
            $table->string('name', 200)->index();
            $table->text('beschreibung');
            $table->text('kurz');
            $table->text('seo');
            $table->index(['regionid', 'lang']);
        });
        Schema::create('xsigns_fewo_reinfirma', function($table){
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('rein_id')->unsigned()->index();
            $table->string('rein_firma', 200)->index();
            $table->string('rein_name', 200);
            $table->string('rein_mail', 250);
            $table->string('rein_tel', 25);
        });
        Schema::create('xsigns_fewo_typ', function($table) {
            $table->engine = 'InnoDB';
            $table->integer('typid')->unsigned()->index();
            $table->string('typen_name',200)->index();
            $table->string('typen_sort',10)->index();
        });
        Schema::create('xsigns_fewo_typlang', function($table) {
            $table->engine = 'InnoDB';
            $table->integer('typid')->unsigned()->index();
            $table->string('lang', 3)->index();
            $table->string('name',200);
            $table->index(['typid', 'lang']);
        });
        Schema::create('xsigns_fewo_vorg', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('vorg_id')->unsigned()->index();
            $table->integer('vorg_objid')->unsigned()->index();
            $table->string('vorg_art', 4)->index();
            $table->date('vorg_datum');
            $table->date('vorg_anreise')->index();
            $table->date('vorg_abreise')->index();
            $table->string('vorg_vorname', 120);
            $table->string('vorg_name', 120);
            $table->string('vorg_mail', 250);
            $table->integer('vorg_gastid')->unsigned()->index();
            $table->decimal('vorg_objpreis', 9, 2)->default(0.00);
            $table->decimal('vorg_leistpreis', 9, 2)->default(0.00);
            $table->decimal('vorg_summe', 9, 2)->default(0.00);
            $table->integer('vorg_erw')->unsigned();
            $table->integer('vorg_kinder')->unsigned();
            $table->integer('vorg_kleinkind')->unsigned();
            $table->decimal('vorg_gebuehr', 9, 2)->default(0.00);
            $table->decimal('vorg_kurtaxe', 9, 2)->default(0.00);
            $table->decimal('vorg_anzahlung', 9, 2)->default(0.00);
            $table->decimal('vorg_kaution', 9, 2)->default(0.00);
            $table->text('vorg_memo');
            $table->text('vorg_ehinweis');
            $table->integer('vorg_eigenid')->unsigned()->index();
            $table->integer('vorg_reinigungid')->unsigned()->index();
            $table->string('vorg_fremdart', 120);
            $table->integer('vorg_fremdartid')->unsigned();
            $table->index(['vorg_objid', 'vorg_id','vorg_art']);
            $table->index(['vorg_anreise','vorg_abreise','vorg_art']);
        });
        Schema::create('xsigns_fewo_vorgleist', function ($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('tstamp')->useCurrent();
            $table->integer('vorgid')->unsigned()->index();
            $table->integer('leistid')->unsigned()->index();
            $table->integer('objid')->unsigned()->index();
            $table->decimal('anzahl',5, 2)->default(0.00);
            $table->decimal('epreis', 9, 2)->default(0.00);
            $table->decimal('summe', 9, 2)->default(0.00);
            $table->decimal('mwst', 5, 2)->default(0.00);
            $table->decimal('mwstbetrag', 9, 2)->default(0.00);
            $table->text('text');
            $table->index(['vorgid', 'leistid']);
        });
        Schema::create('xsigns_fewo_zu',function($table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('zu_id')->unsigned()->index();
            $table->string('zu_name', 200)->index();
            $table->decimal('zu_preis', 7, 2);
            $table->decimal('zu_tagespreis', 7, 2)->default(0.00);
            $table->integer('zu_personen')->unsigned();
            $table->integer('zu_tage')->unsigned();
            $table->integer('zu_abpers')->unsigned();
            $table->integer('zu_abpersan')->unsigned();
            $table->decimal('zu_prozent', 7, 2)->default(0.00);
            $table->integer('zu_kurzbucher')->unsigned();
            $table->integer('zu_tageminus')->unsigned();
            $table->integer('zu_objartid')->unsigned();
            $table->date('zu_von');
            $table->date('zu_bis');
            $table->integer('zu_zeitraumaktiv')->unsigned();
            $table->index(['zu_id', 'zu_objartid']);
        });
         Schema::create('xsigns_fewo_zulang',function($table){
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->timestamp('tstamp')->useCurrent();
            $table->integer('zulng_zuid')->unsigned()->index();
            $table->string('zulng_lang', 3)->index();
            $table->string('zulng_name', 200)->index();
            $table->index(['zulng_zuid', 'zulng_lang']);
        });
        Schema::create('xsigns_fewo_abrechnung',function($table) {
             $table->engine = 'InnoDB';
             $table->increments('id');
             $table->integer('abr_eigenid')->unsigned()->index();
             $table->integer('abr_monat')->unsigned()->index();
             $table->integer('abr_jahr')->unsigned()->index();
             $table->string('abr_liste', 250);
             $table->string('abr_provision', 250);
             $table->string('abr_wartung1', 250);
             $table->string('abr_wartung2', 250);
             $table->string('abr_wartung3', 250);
             $table->string('abr_wartung4', 250);
             $table->integer('abr_download')->unsigned();
             $table->string('abr_art', 120);
             $table->date('abr_datum');
             $table->text('abr_memo');
         });

        Schema::create('xsigns_fewo_slide_shows', function($table)
        {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('slide_show_title');
            $table->text('slide_show_content');
            $table->integer('autoplay')->nullable();
            $table->integer('accessibility')->nullable();
            $table->integer('adaptive_height')->nullable();
            $table->integer('autoplay_speed')->nullable();
            $table->integer('arrows')->nullable();
            $table->string('prev_arrow',250)->nullable();
            $table->string('next_arrow',250)->nullable();
            $table->integer('center_mode')->nullable();
            $table->string('center_padding',10)->nullable();
            $table->string('css_ease',250)->nullable();
            $table->integer('dots')->nullable();
            $table->string('dots_class',250)->nullable();
            $table->integer('draggable')->nullable();
            $table->integer('fade')->nullable();
            $table->integer('focus_on_select')->nullable();
            $table->string('easing',250)->nullable();
            $table->double('edge_friction',9,2)->nullable();
            $table->integer('infinite')->nullable();
            $table->integer('initial_slide')->nullable();
            $table->string('lazy_load',250)->nullable();
            $table->integer('pause_on_focus')->nullable();
            $table->integer('pause_on_hover')->nullable();
            $table->integer('pause_on_dots_hover')->nullable();
            $table->text('responsive');
            $table->integer('rows')->nullable();
            $table->integer('slides_per_row')->nullable();
            $table->integer('slides_to_show')->nullable();
            $table->integer('slides_to_scroll')->nullable();
            $table->integer('speed')->nullable();
            $table->integer('swipe')->nullable();
            $table->integer('touch_move')->nullable();
            $table->integer('touch_threshold')->nullable();
            $table->integer('use_css')->nullable();
            $table->integer('use_transform')->nullable();
            $table->integer('vertical')->nullable();
            $table->integer('vertical_swiping')->nullable();
            $table->integer('rtl')->nullable();
            $table->integer('wait_for_animate')->nullable();
            $table->integer('z_index')->nullable();
            $table->string('slide_show_height',10)->nullable();
            $table->integer('include_jquery')->nullable();
            $table->integer('show_title')->nullable();
            $table->integer('show_desc')->nullable();
            $table->integer('include_thumb')->nullable();
            $table->string('thumb_height',60)->nullable();
            $table->integer('thumb_images')->nullable();
            $table->integer('thumb_top')->nullable();
            $table->integer('show_asimages')->nullable();
            $table->string('asimages_height',10);
        });
    }

    public function down()
    {
        Schema::dropIfExists('xsigns_fewo_abrechnung');
        Schema::dropIfExists('xsigns_fewo_ang');
        Schema::dropIfExists('xsigns_fewo_anglang');
        Schema::dropIfExists('xsigns_fewo_angobj');
        Schema::dropIfExists('xsigns_fewo_art');
        Schema::dropIfExists('xsigns_fewo_artlang');
        Schema::dropIfExists('xsigns_fewo_aus');
        Schema::dropIfExists('xsigns_fewo_auskat');
        Schema::dropIfExists('xsigns_fewo_auskatlang');
        Schema::dropIfExists('xsigns_fewo_auslang');
        Schema::dropIfExists('xsigns_fewo_bew');
        Schema::dropIfExists('xsigns_fewo_bewopt');
        Schema::dropIfExists('xsigns_fewo_bewoptlang');
        Schema::dropIfExists('xsigns_fewo_bewpunkte');
        Schema::dropIfExists('xsigns_fewo_buchung');
        Schema::dropIfExists('xsigns_fewo_entf');
        Schema::dropIfExists('xsigns_fewo_entflang');
        Schema::dropIfExists('xsigns_fewo_galleries');
        Schema::dropIfExists('xsigns_fewo_gast');
        Schema::dropIfExists('xsigns_fewo_ha');
        Schema::dropIfExists('xsigns_fewo_halang');
        Schema::dropIfExists('xsigns_fewo_kunde');
        Schema::dropIfExists('xsigns_fewo_la');
        Schema::dropIfExists('xsigns_fewo_lalang');
        Schema::dropIfExists('xsigns_fewo_le');
        Schema::dropIfExists('xsigns_fewo_leart');
        Schema::dropIfExists('xsigns_fewo_lelang');
        Schema::dropIfExists('xsigns_fewo_obj');
        Schema::dropIfExists('xsigns_fewo_objaus');
        Schema::dropIfExists('xsigns_fewo_objleist');
        Schema::dropIfExists('xsigns_fewo_objentf');
        Schema::dropIfExists('xsigns_fewo_objlang');
        Schema::dropIfExists('xsigns_fewo_objleist');
        Schema::dropIfExists('xsigns_fewo_objstat');
        Schema::dropIfExists('xsigns_fewo_objza');
        Schema::dropIfExists('xsigns_fewo_orte');
        Schema::dropIfExists('xsigns_fewo_preise');
        Schema::dropIfExists('xsigns_fewo_preiselang');
        Schema::dropIfExists('xsigns_fewo_reg');
        Schema::dropIfExists('xsigns_fewo_reglang');
        Schema::dropIfExists('xsigns_fewo_reinfirma');
        Schema::dropIfExists('xsigns_fewo_slide_shows');
        Schema::dropIfExists('xsigns_fewo_typ');
        Schema::dropIfExists('xsigns_fewo_typlang');
        Schema::dropIfExists('xsigns_fewo_vorg');
        Schema::dropIfExists('xsigns_fewo_vorggesendet');
        Schema::dropIfExists('xsigns_fewo_vorgleist');
        Schema::dropIfExists('xsigns_fewo_vorgmit');
        Schema::dropIfExists('xsigns_fewo_zu');
        Schema::dropIfExists('xsigns_fewo_zulang');
        Schema::dropIfExists('xsigns_fewo_objlagen');
        Schema::dropIfExists('xsigns_fewo_objbleist');
    }

}
